modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL = "https://github.com/ochotonida/some-assembly-required/issues"

[[mods]]
modId = "some_assembly_required"
version = "${file.jarVersion}"
displayName = "Some Assembly Required"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/some-assembly-required"
logoFile = "logo.png"
authors = "ochotonida"
credits = "Based on the fabric mod Sandwichable by FoundationGames"
description = '''
Design your own sandwiches!
'''

[[dependencies.some_assembly_required]]
    modId = "forge"
    mandatory = true
    versionRange = "[40.0.30,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.2,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "create"
    mandatory = false
    versionRange = "[0.4.1,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.some_assembly_required]]
    modId = "farmersdelight"
    mandatory = true
    versionRange = "[1.18.2-1.0.4,)"
    ordering = "AFTER"
    side = "BOTH"
